#Lecture 2 Notes
##Reading through the NumPy lecture

[http://quant-econ.net/py/numpy.html]

source activate py27/py35

In [7]:
import numpy as np


array([[ 0.,  0.],
       [ 0.,  0.]])

In [10]:
z = np.zeros(10)
z.shape = (10,1)
z

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [11]:
y = np.zeros(4)
y.shape = (2,2)
y

#there is also np.ones() and np.empty()

array([[ 0.,  0.],
       [ 0.,  0.]])

In [13]:
x = np.linspace(2,4,5) #from 2 to 4 with 5 elements
x

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [15]:
z = np.identity(2) #identity matrix
z

array([[ 1.,  0.],
       [ 0.,  1.]])

In [20]:
z = np.array([10,20])
z

array([10, 20])

In [22]:
z = np.array((10, 20), dtype=float) 
z

array([ 10.,  20.])

In [23]:
z = np.array([[1, 2], [3, 4]]) #creating matrices with np arrays
z

array([[1, 2],
       [3, 4]])

## Array Indexing

In [25]:
z = np.linspace(1,2,5)
z

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [27]:
z[0]

1.0

In [29]:
z[0:2]

array([ 1.  ,  1.25])

In [32]:
z[-1]

2.0

### 2-d array indexing

In [33]:
z = np.array([[1, 2], [3, 4]])

In [35]:
z[0,0]

1

In [36]:
z[0,1]

2

In [37]:
z[0:]

array([[1, 2],
       [3, 4]])

In [39]:
z[:,1]

array([2, 4])

## Array Methods

In [40]:
A = np.array((4,3,2,1))

In [41]:
A

array([4, 3, 2, 1])

In [43]:
A.sort()
A

array([1, 2, 3, 4])

In [44]:
A.sum()

10

In [45]:
A.mean()

2.5

In [46]:
A.max()

4

In [48]:
A.argmax() #index of the maximal element

3

In [50]:
A.cumsum() #cumulative sum of the elements of A

array([ 1,  3,  6, 10])

In [51]:
A.cumprod() #cumulative product of the elements of A

array([ 1,  2,  6, 24])

In [52]:
A.var()

1.25

In [53]:
A.std()

1.1180339887498949

In [57]:
A.shape = (2,2)
A

array([[1, 2],
       [3, 4]])

In [58]:
A.T

array([[1, 3],
       [2, 4]])

###Matrix Multiplication

In [61]:
A = np.ones((2,2))
B = np.ones((2,2))

A

array([[ 1.,  1.],
       [ 1.,  1.]])

In [62]:
np.dot(A,B)

array([[ 2.,  2.],
       [ 2.,  2.]])

###Comparisons

In [63]:
z = np.array([2,3])
y = np.array([2,3])

z == y

array([ True,  True], dtype=bool)

In [65]:
y[0] = 5
z == y

array([False,  True], dtype=bool)

In [66]:
z != y

array([ True, False], dtype=bool)

In [68]:
z = np.linspace(0,10,5)
z

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [69]:
z > 3

array([False, False,  True,  True,  True], dtype=bool)

###Conditional Extraction

In [70]:
b = z > 3
b

array([False, False,  True,  True,  True], dtype=bool)

In [71]:
z[b]

array([  5. ,   7.5,  10. ])

In [72]:
z[z>3]

array([  5. ,   7.5,  10. ])

### Vectorized Functions

In [73]:
z = np.array([1,2,3])
np.sin(z)

array([ 0.84147098,  0.90929743,  0.14112001])

In [77]:
for i in range(2):
    y[i] = np.sin(z[i])

y

array([0, 0])

### **Important note for checking arguments for functions

In [81]:
#np.rank() 

If you click inside the parenthesis, and hit shift+tab once or shift+tab+tab you can get information about the arguments for the function